name: todo_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2
  pinput: ^5.0.1
  url_launcher: ^6.3.1
  dropdown_button2: ^2.3.9
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  vibration: ^3.1.3 
  flutter_svg: ^2.0.17
  image_picker: ^1.1.2
  share_plus: ^11.0.0
  lottie: ^3.3.1

  audioplayers: ^6.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
